# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coro Melod&iacute;as de Esperanza
email: admin@coromelodias.org
description: Sitio Web Oficial de Coro Cristiano Melodías de Esperanza - Barrio San José Alajuela - Costa Rica   
baseurl: "" 
url: "http://www.coromelodias.org"

# Build settings
markdown: kramdown
